### ISSUE TITLE
Any plans to provide preprocessed dataset/pretrained model parameters?

### ISSUE THREAD

**Issue by jyjohnchoi** [taoshen58/glm-codes#1]
Hello. I'm currently trying to reproduce your experimental results and conduct an analysis with them.
Your Readme is very well-organized, but it would be more convenient if you can provide the preprocessed dataset for pretraining or the pre-trained BERT/RoBERTa parameters. 
Can you provide one of them to the public?

Thank you.

**Comment by taoshen58** [comment]
Hi, thanks for your interest in our work. It's been a long time so I cannot find the huge pre-processed data. But I did find RoBERTa_L-based GLM in my hard drive and please get it at [Google Drive](https://drive.google.com/drive/folders/1FqReG7uSzTe0Vos7bx9vhvaoMv6mEqIU?usp=sharing)
